// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgxxoqunumxokpgfbbot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJneHhvcXVudW14b2twZ2ZiYm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzQ5MDUsImV4cCI6MjA3MDgxMDkwNX0.UiVnDt4MLQACylcPE-yfxUDXetbfsU2n_3BN6EyU938";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});